<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CvsSymptomSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('cvs_symptoms')->truncate();
        DB::table('cvs_symptoms')->insert(array_map(fn($r) => [
            'symptom_key'  => $r[0],
            'sort_order'   => $r[1],
            'lang_code'    => $r[2],
            'symptom_text' => $r[3],
            'created_at'   => now(),
            'updated_at'   => now(),
        ], $this->data()));
    }

    private function data(): array
    {
        return [
            ['burning', 1, 'en', 'Burning'],
            ['itching', 2, 'en', 'Itching'],
            ['foreign_body', 3, 'en', 'Feeling of a foreign body'],
            ['tearing', 4, 'en', 'Tearing'],
            ['blinking', 5, 'en', 'Excessive blinking'],
            ['redness', 6, 'en', 'Eye redness'],
            ['pain', 7, 'en', 'Eye pain'],
            ['heavy_eyelids', 8, 'en', 'Heavy eyelids'],
            ['dryness', 9, 'en', 'Dryness'],
            ['blurred_vision', 10, 'en', 'Blurred vision'],
            ['double_vision', 11, 'en', 'Double vision'],
            ['near_vision', 12, 'en', 'Difficulty focusing for near vision'],
            ['light_sensitivity', 13, 'en', 'Increased sensitivity to light'],
            ['halos', 14, 'en', 'Coloured halos around objects'],
            ['worsening_eyesight', 15, 'en', 'Feeling that sight is worsening'],
            ['headache', 16, 'en', 'Headache'],
            ['burning', 1, 'hi', 'आँखों में जलन'],
            ['itching', 2, 'hi', 'खुजली'],
            ['foreign_body', 3, 'hi', 'बाहरी वस्तु का अहसास'],
            ['tearing', 4, 'hi', 'आँखों से पानी आना'],
            ['blinking', 5, 'hi', 'अत्यधिक पलकें झपकना'],
            ['redness', 6, 'hi', 'आँखों का लाल होना'],
            ['pain', 7, 'hi', 'आँखों में दर्द'],
            ['heavy_eyelids', 8, 'hi', 'पलकों का भारीपन'],
            ['dryness', 9, 'hi', 'सूखापन'],
            ['blurred_vision', 10, 'hi', 'धुंधली दृष्टि'],
            ['double_vision', 11, 'hi', 'दोहरा दिखना'],
            ['near_vision', 12, 'hi', 'पास की दृष्टि में कठिनाई'],
            ['light_sensitivity', 13, 'hi', 'प्रकाश के प्रति बढ़ी हुई संवेदनशीलता'],
            ['halos', 14, 'hi', 'वस्तुओं के चारों ओर रंगीन घेरे'],
            ['worsening_eyesight', 15, 'hi', 'दृष्टि बिगड़ने का अहसास'],
            ['headache', 16, 'hi', 'सिरदर्द'],
            ['burning', 1, 'gu', 'આંખોમાં બળતરા (Burning)'],
            ['itching', 2, 'gu', 'ખંજવાળ (Itching)'],
            ['foreign_body', 3, 'gu', 'આંખમાં કંઈક બહારની વસ્તુ હોવાનો અહેસาส (Feeling of a foreign body)'],
            ['tearing', 4, 'gu', 'આંખોમાંથી પાણી આવવું (Tearing)'],
            ['blinking', 5, 'gu', 'વધુ પડતી પલકો ઝપકાવવી (Excessive blinking)'],
            ['redness', 6, 'gu', 'આંખોની લાલાશ (Eye redness)'],
            ['pain', 7, 'gu', 'આંખમાં દુખાવો (Eye pain)'],
            ['heavy_eyelids', 8, 'gu', 'પોપચાનું ભારેપણું (Heavy eyelids)'],
            ['dryness', 9, 'gu', 'શુષ્કતા/કોરું લાગવું (Dryness)'],
            ['blurred_vision', 10, 'gu', 'ઝાંખી દ્રષ્ટિ (Blurred vision)'],
            ['double_vision', 11, 'gu', 'બેવડું દેખાવું (Double vision)'],
            ['near_vision', 12, 'gu', 'નજીકની દ્રષ્ટિ પર ધ્યાન કેન્દ્રિત કરવામાં મુશ્કેલી (Difficulty focusing for near vision)'],
            ['light_sensitivity', 13, 'gu', 'પ્રકાશ પ્રત્યે વધેલી સંવેદનશીલતા (Increased sensitivity to light)'],
            ['halos', 14, 'gu', 'વસ્તુઓની આસપાસ રંગીન કુંડાળા દેખાવા (Coloured halos around objects)'],
            ['worsening_eyesight', 15, 'gu', 'દ્રષ્ટિ બગડી રહી હોય તેવો અહેસาส (Feeling that sight is worsening)'],
            ['headache', 16, 'gu', 'માથાનો દુખાવો (Headache)'],
            ['burning', 1, 'mr', 'डोळ्यांची जळजळ (Burning)'],
            ['itching', 2, 'mr', 'खाज सुटणे (Itching)'],
            ['foreign_body', 3, 'mr', 'डोळ्यात काहीतरी गेल्यासारखे वाटणे (Feeling of a foreign body)'],
            ['tearing', 4, 'mr', 'डोळ्यातून पाणी येणे (Tearing)'],
            ['blinking', 5, 'mr', 'वारंवार पापण्यांची हालचाल/मिटणे (Excessive blinking)'],
            ['redness', 6, 'mr', 'डोळे लाल होणे (Eye redness)'],
            ['pain', 7, 'mr', 'डोळ्यांत दुखणे (Eye pain)'],
            ['heavy_eyelids', 8, 'mr', 'पापण्या जड होणे (Heavy eyelids)'],
            ['dryness', 9, 'mr', 'कोरडेपणा (Dryness)'],
            ['blurred_vision', 10, 'mr', 'धूसर दृष्टी (Blurred vision)'],
            ['double_vision', 11, 'mr', 'दुहेरी दिसणे (Double vision)'],
            ['near_vision', 12, 'mr', 'जवळच्या दृष्टीवर लक्ष केंद्रित करण्यात अडचण (Difficulty focusing for near vision)'],
            ['light_sensitivity', 13, 'mr', 'प्रकाशाची संवेदनशीलता वाढणे (Increased sensitivity to light)'],
            ['halos', 14, 'mr', 'वस्तूंभोवती रंगीत कडे दिसणे (Coloured halos around objects)'],
            ['worsening_eyesight', 15, 'mr', 'दृष्टी कमी होत असल्याचे वाटणे (Feeling that sight is worsening)'],
            ['headache', 16, 'mr', 'डोकेदुखी (Headache)'],
            ['burning', 1, 'bn', 'চোখে জ্বালাপোড়া (Burning)'],
            ['itching', 2, 'bn', 'চুলকানি (Itching)'],
            ['foreign_body', 3, 'bn', 'চোখে বাইরের কিছু আছে এমন অনুভূতি (Feeling of a foreign body)'],
            ['tearing', 4, 'bn', 'চোখ দিয়ে জল পড়া (Tearing)'],
            ['blinking', 5, 'bn', 'অতিরিক্ত পলক ফেলা (Excessive blinking)'],
            ['redness', 6, 'bn', 'চোখ লাল হওয়া (Eye redness)'],
            ['pain', 7, 'bn', 'চোখে ব্যথা (Eye pain)'],
            ['heavy_eyelids', 8, 'bn', 'চোখের পাতা ভারী বোধ হওয়া (Heavy eyelids)'],
            ['dryness', 9, 'bn', 'শুষ্কতা (Dryness)'],
            ['blurred_vision', 10, 'bn', 'ঝাপসা দৃষ্টি (Blurred vision)'],
            ['double_vision', 11, 'bn', 'দ্বৈত দৃষ্টি/একই জিনিস দুটি দেখা (Double vision)'],
            ['near_vision', 12, 'bn', 'কাছের জিনিসের ওপর দৃষ্টি নিবদ্ধ করতে অসুবিধা (Difficulty focusing for near vision)'],
            ['light_sensitivity', 13, 'bn', 'আলোর প্রতি সংবেদনশীলতা বৃদ্ধি (Increased sensitivity to light)'],
            ['halos', 14, 'bn', 'বস্তুর চারপাশে রঙিন আভা বা বলয় দেখা (Coloured halos around objects)'],
            ['worsening_eyesight', 15, 'bn', 'দৃষ্টিশক্তি কমে যাচ্ছে এমন অনুভূতি (Feeling that sight is worsening)'],
            ['headache', 16, 'bn', 'মাথাব্যথা (Headache)'],
            ['burning', 1, 'as', 'চকু জ্বলা-পোৰা কৰা (Burning)'],
            ['itching', 2, 'as', 'চকু খজুওৱা (Itching)'],
            ['foreign_body', 3, 'as', 'চকুত কিবা বাহিৰা বস্তু থকা যেন লগা (Feeling of a foreign body)'],
            ['tearing', 4, 'as', 'চকুৰ পৰা পানী ওলোৱা (Tearing)'],
            ['blinking', 5, 'as', 'অতিৰিক্তভাৱে চকুৰ পতা লৰচৰ কৰা (Excessive blinking)'],
            ['redness', 6, 'as', 'চকু ৰঙা পৰা (Eye redness)'],
            ['pain', 7, 'as', 'চকুৰ বিষ (Eye pain)'],
            ['heavy_eyelids', 8, 'as', 'চকুৰ পতা গধুৰ হোৱা (Heavy eyelids)'],
            ['dryness', 9, 'as', 'চকু শুকাই যোৱা (Dryness)'],
            ['blurred_vision', 10, 'as', 'চকুৰে ধোঁৱাকোৱা দেখা (Blurred vision)'],
            ['double_vision', 11, 'as', 'এটা বস্তু দুটা দেখা (Double vision)'],
            ['near_vision', 12, 'as', 'ওচৰৰ বস্তুৰ ওপৰত দৃষ্টি কেন্দ্ৰীভূত কৰাত অসুবিধা (Difficulty focusing for near vision)'],
            ['light_sensitivity', 13, 'as', 'পোহৰৰ প্ৰতি সংবেদনশীলতা বৃদ্ধি (Increased sensitivity to light)'],
            ['halos', 14, 'as', 'বস্তুৰ চাৰিওফালে ৰঙীন চক্ৰ দেখা (Coloured halos around objects)'],
            ['worsening_eyesight', 15, 'as', 'দৃষ্টিশক্তি ক্ৰমান্বয়ে হ্ৰাস পোৱা যেন লগা (Feeling that sight is worsening)'],
            ['headache', 16, 'as', 'মূৰৰ বিষ (Headache)'],
            ['burning', 1, 'or', 'ଆଖି ପୋଡ଼ାଜଳା କରିବା (Burning)'],
            ['itching', 2, 'or', 'କୁଣ୍ଡେଇ ହେବା (Itching)'],
            ['foreign_body', 3, 'or', 'ଆଖିରେ କିଛି ବାହାର ଜିନିଷ ପଶିଥିବା ପରି ଅନୁଭବ ହେବା (Feeling of a foreign body)'],
            ['tearing', 4, 'or', 'ଆଖିରୁ ଲୁହ ବାହାରିବା (Tearing)'],
            ['blinking', 5, 'or', 'ଅତ୍ୟଧିକ ଆଖିପତା ପକାଇବା (Excessive blinking)'],
            ['redness', 6, 'or', 'ଆଖି ଲାଲ୍ ପଡ଼ିବା (Eye redness)'],
            ['pain', 7, 'or', 'ଆଖିରେ ଯନ୍ତ୍ରଣା (Eye pain)'],
            ['heavy_eyelids', 8, 'or', 'ଆଖିପତା ଭାରି ଲାଗିବା (Heavy eyelids)'],
            ['dryness', 9, 'or', 'ଶୁଷ୍କତା (Dryness)'],
            ['blurred_vision', 10, 'or', 'ଝାପସା ଦୃଷ୍ଟିଶକ୍ତି (Blurred vision)'],
            ['double_vision', 11, 'or', 'ଗୋଟିଏ ଜିନିଷ ଦୁଇଟି ଦେଖାଯିବା (Double vision)'],
            ['near_vision', 12, 'or', 'ପାଖ ଜିନିଷ ଉପରେ ଦୃଷ୍ଟି କେନ୍ଦ୍ରୀଭୂତ କରିବାରେ ଅସୁବିଧା (Difficulty focusing for near vision)'],
            ['light_sensitivity', 13, 'or', 'ଆଲୋକ ପ୍ରତି ସମ୍ବେଦନଶୀଳତା ବୃଦ୍ଧି (Increased sensitivity to light)'],
            ['halos', 14, 'or', 'ବସ୍ତୁ ଚାରିପାଖରେ ରଙ୍ଗୀନ ବଳୟ ଦେଖାଯିବା (Coloured halos around objects)'],
            ['worsening_eyesight', 15, 'or', 'ଦୃଷ୍ଟିଶକ୍ତି ଖରାପ ହେଉଥିବା ପରି ଅନୁଭବ ହେବା (Feeling that sight is worsening)'],
            ['headache', 16, 'or', 'ମୁଣ୍ଡବିନ୍ଧା (Headache)'],
            ['burning', 1, 'ta', 'கண்கள் எரிச்சல் (Burning)'],
            ['itching', 2, 'ta', 'அரிப்பு (Itching)'],
            ['foreign_body', 3, 'ta', 'கண்ணில் ஏதோ ஒரு வெளிப்பொருள் இருப்பது போன்ற உணர்வு (Feeling of a foreign body)'],
            ['tearing', 4, 'ta', 'கண்ணீர் வடிதல் (Tearing)'],
            ['blinking', 5, 'ta', 'அதிகப்படியான கண் இமைத்தல் (Excessive blinking)'],
            ['redness', 6, 'ta', 'கண் சிவத்தல் (Eye redness)'],
            ['pain', 7, 'ta', 'கண் வலி (Eye pain)'],
            ['heavy_eyelids', 8, 'ta', 'கண் இமைகள் கனமாக இருப்பது (Heavy eyelids)'],
            ['dryness', 9, 'ta', 'வறட்சி (Dryness)'],
            ['blurred_vision', 10, 'ta', 'மங்கலான பார்வை (Blurred vision)'],
            ['double_vision', 11, 'ta', 'இரட்டைப் பார்வை (Double vision)'],
            ['near_vision', 12, 'ta', 'அருகிலுள்ள பார்வையில்ல கவனம் செலுத்துவதில் சிரமம் (Difficulty focusing for near vision)'],
            ['light_sensitivity', 13, 'ta', 'ஒளியின் மீதான அதிகப்படியான உணர்திறன் (Increased sensitivity to light)'],
            ['halos', 14, 'ta', 'பொருட்களைச் சுற்றி வண்ணமயமான ஒளிவட்டங்கள் தெரிதல் (Coloured halos around objects)'],
            ['worsening_eyesight', 15, 'ta', 'பார்வை குறைந்து வருவது போன்ற உணர்வு (Feeling that sight is worsening)'],
            ['headache', 16, 'ta', 'தலைவலி (Headache)'],
            ['burning', 1, 'te', 'కళ్ల మంటలు (Burning)'],
            ['itching', 2, 'te', 'దురద (Itching)'],
            ['foreign_body', 3, 'te', 'కంటిలో ఏదో నలుసు పడినట్లు అనిపించడం (Feeling of a foreign body)'],
            ['tearing', 4, 'te', 'కళ్ల నుండి నీరు కారడం (Tearing)'],
            ['blinking', 5, 'te', 'మితిమీరిన రెప్పపాటు (Excessive blinking)'],
            ['redness', 6, 'te', 'కళ్లు ఎర్రబడటం (Eye redness)'],
            ['pain', 7, 'te', 'కంటి నొప్పి (Eye pain)'],
            ['heavy_eyelids', 8, 'te', 'రెప్పలు బరువుగా అనిపించడం (Heavy eyelids)'],
            ['dryness', 9, 'te', 'కళ్లు పొడిబారడం (Dryness)'],
            ['blurred_vision', 10, 'te', 'మసక చూపు (Blurred vision)'],
            ['double_vision', 11, 'te', 'రెండేసిగా కనిపించడం (Double vision)'],
            ['near_vision', 12, 'te', 'దగ్గరి వస్తువులపై దృష్టి పెట్టడంలో ఇబ్బంది (Difficulty focusing for near vision)'],
            ['light_sensitivity', 13, 'te', 'వెలుతురును తట్టుకోలేకపోవడం (Increased sensitivity to light)'],
            ['halos', 14, 'te', 'వస్తువుల చుట్టూ రంగుల వలయాలు కనిపించడం (Coloured halos around objects)'],
            ['worsening_eyesight', 15, 'te', 'చూపు మందగిస్తున్నట్లు అనిపించడం (Feeling that sight is worsening)'],
            ['headache', 16, 'te', 'తలనొప్పి (Headache)'],
            ['burning', 1, 'ml', 'കണ്ണ് നീറ്റൽ (Burning)'],
            ['itching', 2, 'ml', 'ചൊറിച്ചിൽ (Itching)'],
            ['foreign_body', 3, 'ml', 'കണ്ണിൽ എന്തോ കരട് പോയതുപോലെയുള്ള തോന്നൽ (Feeling of a foreign body)'],
            ['tearing', 4, 'ml', 'കണ്ണിൽ നിന്ന് വെള്ളം വരിക (Tearing)'],
            ['blinking', 5, 'ml', 'അമിതമായി കണ്ണ് ചിമ്മുക (Excessive blinking)'],
            ['redness', 6, 'ml', 'കണ്ണ് ചുവക്കുക (Eye redness)'],
            ['pain', 7, 'ml', 'കണ്ണ് വേദന (Eye pain)'],
            ['heavy_eyelids', 8, 'ml', 'കൺപോളകൾക്ക് കനം തോന്നുക (Heavy eyelids)'],
            ['dryness', 9, 'ml', 'കണ്ണ് വരൾച്ച (Dryness)'],
            ['blurred_vision', 10, 'ml', 'മങ്ങിയ കാഴ്ച (Blurred vision)'],
            ['double_vision', 11, 'ml', 'ഇരട്ടക്കാഴ്ച (Double vision)'],
            ['near_vision', 12, 'ml', 'അടുത്തുള്ള കാഴ്ചയിൽ ശ്രദ്ധ കേന്ദ്രീകരിക്കാനുള്ള ബുദ്ധിമുട്ട് (Difficulty focusing for near vision)'],
            ['light_sensitivity', 13, 'ml', 'വെളിച്ചത്തോടുള്ള അമിത സംവേദനക്ഷമത (Increased sensitivity to light)'],
            ['halos', 14, 'ml', 'വസ്തുക്കൾക്ക് ചുറ്റും നിറമുള്ള വളയങ്ങൾ കാണുക (Coloured halos around objects)'],
            ['worsening_eyesight', 15, 'ml', 'കാഴ്ചശക്തി കുറയുന്നതായുള്ള തോന്നൽ (Feeling that sight is worsening)'],
            ['headache', 16, 'ml', 'തലവേദന (Headache)'],
            ['burning', 1, 'kn', 'ಕಣ್ಣು ಉರಿ (Burning)'],
            ['itching', 2, 'kn', 'ಕಣ್ಣು ತುರಿಕೆ (Itching)'],
            ['foreign_body', 3, 'kn', 'ಕಣ್ಣಿನಲ್ಲಿ ಯಾವುದೋ ಹೊರವಸ್ತು ಇರುವಂತಹ ಅನುಭವ (Feeling of a foreign body)'],
            ['tearing', 4, 'kn', 'ಕಣ್ಣೀರು ಸುರಿಯುವುದು (Tearing)'],
            ['blinking', 5, 'kn', 'ಅತಿಯಾಗಿ ಕಣ್ಣು ಮಿಟುಕಿಸುವುದು (Excessive blinking)'],
            ['redness', 6, 'kn', 'ಕಣ್ಣು ಕೆಂಪಾಗುವುದು (Eye redness)'],
            ['pain', 7, 'kn', 'ಕಣ್ಣು ನೋವು (Eye pain)'],
            ['heavy_eyelids', 8, 'kn', 'ಕಣ್ಣುರೆಪ್ಪೆಗಳು ಭಾರವೆನಿಸುವುದು (Heavy eyelids)'],
            ['dryness', 9, 'kn', 'ಕಣ್ಣು ಒಣಗುವುದು (Dryness)'],
            ['blurred_vision', 10, 'kn', 'ಮಂಜಾದ ದೃಷ್ಟಿ (Blurred vision)'],
            ['double_vision', 11, 'kn', 'ಎರಡಾಗಿ ಕಾಣುವುದು (Double vision)'],
            ['near_vision', 12, 'kn', 'ಹತ್ತಿರದ ದೃಷ್ಟಿಯ ಮೇಲೆ ಗಮನ ಕೇಂದ್ರೀಕರಿಸಲು ಕಷ್ಟವಾಗುವುದು (Difficulty focusing for near vision)'],
            ['light_sensitivity', 13, 'kn', 'ಬೆಳಕಿಗೆ ಅತಿಯಾದ ಸಂವೇದನಾಶೀಲತೆ (Increased sensitivity to light)'],
            ['halos', 14, 'kn', 'ವಸ್ತುಗಳ ಸುತ್ತ ಬಣ್ಣದ ಪ್ರಭಾವಲಯಗಳು ಕಾಣುವುದು (Coloured halos around objects)'],
            ['worsening_eyesight', 15, 'kn', 'ದೃಷ್ಟಿ ಹದಗೆಡುತ್ತಿದೆ ಎಂಬ ಭಾವನೆ (Feeling that sight is worsening)'],
            ['headache', 16, 'kn', 'ತಲೆನೋವು (Headache)'],
        ];
    }
}
